name = "iqueue"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = ".svelte-kit/cloudflare/static"

routes = [
  { pattern = "iqueue.prestalife.net/*", custom_domain = true }
]
